services:
  - type: web
    name: sanket-backend
    env: python
    buildCommand: "apt-get update && apt-get install -y libgl1-mesa-glx libgles2-mesa libglib2.0-0 || true && pip install -r backend/requirements.txt"
    startCommand: "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12


